# Generated by Django 4.2.5 on 2023-10-03 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_remove_analyzresult_predcit'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzresult',
            name='predict',
            field=models.CharField(default=datetime.datetime(2023, 10, 3, 11, 11, 31, 203801, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
